// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("jargon.apiConsole")>]
[<assembly: AssemblyProductAttribute("jargon.api")>]
[<assembly: AssemblyDescriptionAttribute("first year architecture machine")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "jargon.apiConsole"
    let [<Literal>] AssemblyProduct = "jargon.api"
    let [<Literal>] AssemblyDescription = "first year architecture machine"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
